language: go

matrix:
  include:
    - language: java
      jdk: openjdk8

go:
  - "1.12"

script:
  - mvn clean package -f test_hessian/pom.xml
  - mvn clean package -f test_dubbo/pom.xml
  - go fmt && [[ -z `git status -s` ]]
  - sh before_validate_license.sh
  - chmod u+x /tmp/tools/license/license-header-checker
  - /tmp/tools/license/license-header-checker -v -a -r -i vendor  /tmp/tools/license/license.txt . go  && [[ -z `git status -s` ]]
  - GO111MODULE=on && go mod vendor && go test -race -v && go test -bench . -race -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=27a5eb4510c8cf913b67a72832549b123a8c44655483d20443515604669de0ae
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=8250008579ed1defda3a44fb8608a38d81a55700fdfb15466315a90a7dd2045f
